# Generated by Django 3.2.12 on 2022-05-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_jobassignment_jobs_jobtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobassignment',
            name='assignment_status',
            field=models.CharField(choices=[('assigned', 'assigned'), ('in_progress', 'in_progress'), ('unassigned', 'unassigned'), ('completed', 'completed')], default='assigned', max_length=250),
        ),
        migrations.AddField(
            model_name='jobassignment',
            name='completed_time',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
