# Generated by Django 3.2.12 on 2022-05-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20220526_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='is_colpleted',
            new_name='is_completed',
        ),
    ]
