# Generated by Django 3.2.12 on 2022-05-26 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_is_colpleted_jobs_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobassignment',
            old_name='owner',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='owner',
            new_name='user_id',
        ),
    ]
