# Generated by Django 3.2.12 on 2022-05-26 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20220526_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='estimating_completing_hour',
        ),
    ]
